### ISSUE TITLE
Specify a aws profile and see output of script

### ISSUE THREAD

**Issue by sentinelmangcp** [janiko71/aws-inventory#24]
Hi, I ran the inventory script however it took a long time so I exited. I have about ten accounts in my local aws credentials. I would like to specific --profile for one account. Also a secondary thing is to see the output of the running script if possible. Let me know. Thanks!

**Comment by janiko71** [comment]
Hi, thank you for your feedback. 
1) Yes, profile could be added as parameter, it's a good idea. 
2) I understand for the output, but unfortunately it slows down the code execution :( That's why I replaced the output by a progression indicator.
You can always `tail -f` the log file, as an alternative.

**Comment by janiko71** [comment]
Hi, I've added the 'profile' support in argument. But I had to change the default arguments structure, see [Wiki](https://github.com/janiko71/aws-inventory/wiki/How-to-use-it%3F).

If you want, you can test it, the code is in the 'dev' branch.

**Comment by janiko71** [comment]
Hi, the profile parameter has been added in the 'dev' branch. The command line arguments can be found [here](https://github.com/janiko71/aws-inventory/wiki/How-to-use-it%3F).
