### ISSUE TITLE
output format only accept json

### ISSUE THREAD

**Issue by marcos-wiris** [janiko71/aws-inventory#26]
Hi

I don't know If this is an issue, but output always is json, and Im interested to use other options like text or table. I config inside AWS cli this option, but I can't see If exist any form to pass this option to the script. 

Thanks

**Comment by janiko71** [comment]
Thank you for your interest in my project :) That's an interesting question. The JSON output is a choice. It's not that I like JSON, it's because we are facing unstructured and (sometimes) non-coherent datas. Let me explain: each service is different and is managed by different teams, and inventories can have different structures. And even when the structure is known, the content format can be heterogeneous. 

See https://github.com/janiko71/aws-cloudtrail-elasticsearch for some examples. 

Here, it's not the format matters but the structure of datas: there's no "universal" answer to the functions called in this inventory. For one unique service, it make sense to choose between json, text, table format because you have only one output structure,, but when the datas are heterogeneous, the best option is to use JSON or XML. 

My conclusion was that, for heterogeneous services, the only usabla option was JSON. After that, you can transform it in whatever you want.

**Comment by marcos-wiris** [comment]
ok, in this case I don't know If can be interesting to offer this feature only selecting services. Anyway Im agree with you conclusion, so I will use jq to filter data

Thanks for your time!
