### ISSUE TITLE
functions locations confusion

### ISSUE THREAD

**Issue by ghost** [janiko71/aws-inventory#45]
Hi, is there any reason why kms is in iam.py rather than its own module? elb, elbv2 in networking rather than compute? I'm also trying to add IAM inventory, managed to do users list and groups list, now trying to combine the two - can you think of a way to nest one or the other (e.g. users list under group, or group list under each user?) - 'list-users-for-group' from aws' cli is not really helpful here (no common keys?)

**Comment by janiko71** [comment]
Hi Dawid, no confusion here, I'm just trying to have the same logic than AWS console, but things may have changed since the first version of this tool. For KMS, it should be now in a "security.py" file maybe (with certificate manager, cloudHSM, etc.). As for IAM, I think it should not be included here, but have its own tool, because of the security rimplications. However, if you want to combine lists, you can have a look into analytics.py/Elastic Map Reduce, it may help. 
Thank you for your interest!

**Comment by janiko71** [comment]
No more relevant with the new version.
